In [1]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns 

In [16]:
df = pd.read_excel(r"C:\Users\admin\Desktop\Terro281%29.xlsx", sheet_name='sheet1')
df.head(2)

CRIME_RATE   AGE  INDUS    NOX  DISTANCE  TAX  PTRATIO  AVG_ROOM  LSTAT  \
0        6.32  65.2   2.31  0.538         1  296     15.3     6.575   4.98   
1        4.31  78.9   7.07  0.469         2  242     17.8     6.421   9.14   

   AVG_PRICE  
0       24.0  
1       21.6

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   CRIME_RATE  506 non-null    float64
 1   AGE         506 non-null    float64
 2   INDUS       506 non-null    float64
 3   NOX         506 non-null    float64
 4   DISTANCE    506 non-null    int64  
 5   TAX         506 non-null    int64  
 6   PTRATIO     506 non-null    float64
 7   AVG_ROOM    506 non-null    float64
 8   LSTAT       506 non-null    float64
 9   AVG_PRICE   506 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 39.7 KB


`Standardzing the data 

In [11]:
from sklearn.preprocessing import StandardScaler 

# define standard scaler 
scaler = StandardScaler() 
  
# transform data 
df1 = scaler.fit_transform(df)

In [12]:
df1

array([[ 0.49619694, -0.12001342, -1.2879095 , ...,  0.41367189,
        -1.0755623 ,  0.15968566],
       [-0.19257344,  0.36716642, -0.59338101, ...,  0.19427445,
        -0.49243937, -0.10152429],
       [ 1.02733827, -0.26581176, -0.59338101, ...,  1.28271368,
        -1.2087274 ,  1.32424667],
       ...,
       [ 1.55847961,  0.79744934,  0.11573841, ...,  0.98496002,
        -0.98304761,  0.14880191],
       [ 0.70865347,  0.73699637,  0.11573841, ...,  0.72567214,
        -0.86530163, -0.0579893 ],
       [ 1.59960023,  0.43473151,  0.11573841, ..., -0.36276709,
        -0.66905833, -1.15724782]])

In [20]:
from sklearn.model_selection import train_test_split


X = df.drop('AVG_ROOM', axis=1)  # features
y = df['AVG_PRICE']  # target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
print(type(df))


<class 'pandas.core.frame.DataFrame'>


In [22]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [23]:
lr

LinearRegression()

In [25]:
lr.fit(X_train,y_train)

LinearRegression()

In [26]:
X_test

CRIME_RATE    AGE  INDUS    NOX  DISTANCE  TAX  PTRATIO  LSTAT  AVG_PRICE
173        3.64   84.1   4.05  0.510         5  296     16.6   9.04       23.6
274        0.33   32.9   6.41  0.447         4  254     17.6   3.53       32.4
491        1.43   98.8  27.74  0.609         4  711     20.1  18.07       13.6
72         1.09    7.8  10.81  0.413         4  305     19.2   5.52       22.8
452        9.14   91.8  18.10  0.713        24  666     20.2  17.27       16.1
..          ...    ...    ...    ...       ...  ...      ...    ...        ...
412        4.47  100.0  18.10  0.597        24  666     20.2  34.37       17.9
436        9.76   93.3  18.10  0.740        24  666     20.2  18.05        9.6
411        5.84  100.0  18.10  0.597        24  666     20.2  21.22       17.2
86         6.42   45.1   4.49  0.449         3  247     18.5  12.86       22.5
75         8.23   45.0  12.83  0.437         5  398     18.7   8.94       21.4

[102 rows x 9 columns]

In [27]:
y_test

173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
       ... 
412    17.9
436     9.6
411    17.2
86     22.5
75     21.4
Name: AVG_PRICE, Length: 102, dtype: float64

In [37]:
single_prediction_input = X_test.iloc[1].values.reshape(1, -1)
prediction = lr.predict(single_prediction_input)


C:\Users\admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [38]:
prediction

array([32.4])

In [43]:
m = lr.coef_
m

array([-1.06395605e-16,  1.67777039e-17, -1.66877118e-16, -3.89862838e-15,
        3.80488564e-16, -2.39733721e-17, -5.41102646e-17, -5.59949222e-16,
        1.00000000e+00])

In [44]:
b = lr.intercept_
b

1.0658141036401503e-14

# Y =mx + b

